# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9sMbG4Y5_o-fwh1nwIEo0-JRDnTO1s8
"""

import numpy as py
#creating array
arr=np.array([1,2,3,4,5])
print(arr)
zeros_arr=np.zeros((3,3),dtype=int)
print(zeros_arr)
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)
arange_arr=np.arange(10)
print(arange_arr)
#manuplating array
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
sliced_arr=arr[2:4]
print(sliced_arr)
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])
a3=np.vstack(a1+a2)
print(a3)
a3=np.stack(a1+a2)
print(a3)
b=np.split(a1,2)
print(b)
n=np.array([[1,2],[3,4]])
c=n.T
print(c)
#linear algebra with numpy
v1=np.array([[1,2],[3,4]])
v2=np.array([[5,6],[7,8]])
v3=np.dot(v1,v2)
print(v3)
v4=np.linalg.eig(v3)
print(v4)



a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])
a3=np.add(a1,a2)
print(a3)

a1=np.array([1,2,3,4])
print(a1+3)

a1=np.array([[1,2,3],[4,5,6]])
b=np.sum(a1)
a2=np.array([[1,2,3],[4,5,6]])
print(b)
b=np.sum(a1+a2)
print(b)
print(np.sum(a1,axis=0))
print(np.sum(a1,axis=0))

#statistical operations
a1=np.array([1,2,3,4,5])
m=np.mean(a1)
m2=np.median(a1)
v1=np.var(a1)
sd=np.std(a1)
print(m,m2,v1,sd)

d=np.loadtxt("/content/1 2 3.txt")
d=np.savetxt("/content/date.txt",d)
print(d)

import matplotlib.pyplot as plt
a=np.array([1,2,3,4,5,6,7,8,9,10])

plt.plot(a)

#importing pandas
import pandas as pd
a=["vasanthi","dhana","lalitha","vani","usha","devi"]
r=pd.Series(a,index=[44,45,33,42,41,23])
print(r)
df=pd.read_csv("/content/Rohit-Sharma-All-International-Cricket-Centuries.csv",sep=" , ")
print(df)



import pandas as pd
f=pd.read_csv("/content/txtfile (1).txt")

print(f)

import pandas as pd
f=pd.read_csv("/content/txtfile (1).txt")
print(f.loc[1])#which row ,col





df=pd.read_excel("/content/Historicalinvesttemp.xlsx")
print(df)

df=pd.read_excel("/content/Historicalinvesttemp.xlsx",sheet_name=1)
print(df)

df=pd.read_csv("/content/csvfile.csv")
mv=df['Data_value'].mean()
df=df.fillna(mv)
print(df)

df=pd.read_csv("/content/csvfile (1).csv")
print(df)
df.shape

df=pd.read_csv("/content/csvfile (1).csv")
true=df.tail(10)
for i in range(22188,22178,-1):
  df.drop([i],axis=0, inplace=True) #removing those 10 values from original dataset
true.to_csv("manual_testing.csv")
ma=pd.read_csv("/content/manual_testing.csv")
print(ma.groupby(['Subject'])['UNITS'].count())

df=pd.read_csv("/content/csvfile (1).csv")
df=df.drop_duplicates()
print(df)
df.head(2)

_pip install numpy

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([41,42,43,44,45,63,51,18,11,12])
w=np.array([1,2,3,4,5,6,7,8,9,10])
plt.scatter(runs,w,color='orange')
plt.title('INDvsAUS_SCORE')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)
runs_i=np.array([25,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
plt.subplot(2,1,2)#row,col,index
plt.plot(overs,runs_i,color='blue',label='India')
plt.legend(loc='best')
plt.subplot(2,1,1)

plt.plot(overs_a,runs_a,color='yellow',label='Aus')

plt.legend(loc='best')
plt.show()

import matplotlib.pyplot as plt
a=[230,568,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]
profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth='3',label='CompanyA',marker='X',ms='15',mec='r')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label='CompanyB',marker='H')



import numpy as np
import matplotlib.pyplot as plt
tiger=np.linspace(-2*np.pi, 2*np.pi, 50)
print(tiger)
plt.plot(tiger,np.sin(tiger),color='black')#x,y,color,lable
plt.title("sinx")

a=np.array([23,2,4,25])
labe=["AIML","PYTHON","NUMPY","PANDAS"]
col=["black","violet","yellow","pink"]

explo=[0,0.3,0,0]
plt.pie(a,labels=labe,explode=explo,startangle=360,colors=col,textprops={'fontsize' : 21})
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
d=pd.read_excel('/content/ex.xlsx')
print(d)
mv=d['Temp'].mean()
print("the mean of the temperstures is"mv)
c=np.max(d['Temp'])
a=d.loc[d['Temp'].idxmax(),'Day']
print("the max temp is ",c,"on the day",a)
e=np.min(d['Temp'])
l=d.loc[d['Temp'].idxmin(),'Day']
print("the max temp is ",e,"on the day",l)
threshold=17
v=(d['Temp']>threshold).sum()
print(v)
plt.plot(d['Day'],d['Temp'],color='black',marker='*')
plt.title('Temperature analysis (deg cel)')
plt.xlabel('Day')
plt.ylabel('Temperature')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
TimestampSeries=sns.load_dataset("tips")
print(a.head(10))
sns.scatterplot(x="",y="Day",data=tips)
plt.title("scatter plot of total bill vs tip")
plt.xlabel("total bill ($)")
plt.ylabel("tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
print(tips.head(10))
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("scatter plot of total bill vs tip")
plt.xlabel("total bill ($)")
plt.ylabel("tip ($)")
plt.show()

iris=sns.load_dataset("iris")
print(iris.head(10))
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation heatmap of iris dataset")
plt.show()

attention=sns.load_dataset("attention")
print(attention.head(10))
correlation_matrix=attention.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation heatmap of attention  dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
a=sns.load_dataset("anagrams")
print(a.head(10))
sns.scatterplot(x="subidr",y="num1",data=a)
plt.title("anagrams")
plt.xlabel("subidr")
plt.ylabel("num1")
plt.show()